config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'
  
  devise_for :users, controllers: { sessions: 'users/sessions' }, path_names: {sign_in: :login, sign_out: :logout, sign_up: :signup}

  resource :feedback, only: %i[show create], controller: :feedback

  resources :badges, only: :index do

    collection do
      get :own
    end
  end
  
  resources :tests, only: :index do
    
    member do
      post :start
    end
  end
  
  namespace :admin do
    resources :badges
    resources :rules
    root to: 'tests#index'
    get 'gists', to: "gists#index" 
    resources :tests do
      patch 'update_inline', to: "tests#update_inline", on: :member
      resources :questions, except: [:index], shallow: true do
        resources :answers, except: [:index], shallow: true
      end
    end
  end
  
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post 'gists', to: "gists#create"
    end
  end
      
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users

  enum rule: { all_of_category: 'All of category',
               all_of_level: 'All of level',
               on_first_try: 'On first try' }
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[edit update destroy show]

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, success: "Badge created"
    else
      render :new
    end
  end

  def index
    @badges = Badge.all
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :image, :rule, :rule_option)
  end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end

  def own
    @badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<div class="col mt-3">
  <div class="card bg-light">
    <div class="card-body">
      <h5><%= link_to badge.title, admin_badge_path(badge), class: "card-title" %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= image_tag badge.image %></h6>

      <div class="list-group list-group-horizontal">
        <%= link_to t('edit'),
                    edit_admin_badge_path(badge),
                    class: 'list-group-item bg-secondary text-white' %>
        <%= link_to t('delete'),
                    admin_badge_path(badge),
                    method: :delete,
                    class: 'list-group-item bg-danger text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/badges/_form.html.erb
<div class="row mt-3">
  <div class="col col-md-4">
    <%= render 'shared/errors', resource: @test %>
    <div class="card border-secondary bg-light">
      <div class="card-body">
        <%= form_with model: [:admin, @badge] do |form| %>
          <div class="form-group">
            <p>
              <%= form.label :title %>
              <%= form.text_field :title, class: "form-control" %>
            </p>

            <p>
              <%= form.label :image %>
              <%= form.url_field :image, class: "form-control" %>
            </p>

            <p>
              <%= form.label :rule %>
              <%= form.select :rule, Badge.rules.values, class: "form-control" %>
            </p>

            <p>
              <%= form.label :rule_option %>
              <%= form.number_field :rule_option %>
            </p>

            <%= form.submit class:'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/badges/edit.html.erb
<h1>Edit Badge</h1>
<%= render 'form' %>

<%= link_to 'Create rule', new_admin_rule_path %>

app/views/admin/badges/index.html.erb
<h1 class="text-center mt-3">All badges</h1>

<%= link_to 'Create badge', new_admin_badge_path, class: 'btn btn-secondary mb-2' %>

<div class="row row-cols-3">
  <%= render @badges %>
</div>

app/views/admin/badges/new.html.erb
<h1>Create Badge</h1>
<%= render 'form' %>

<%= link_to 'Create rule', new_admin_rule_path %>

app/views/admin/badges/show.html.erb
<%= render @badge %>