config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'
  
  devise_for :users, controllers: { sessions: 'users/sessions' }, path_names: {sign_in: :login, sign_out: :logout, sign_up: :signup}

  resource :feedback, only: %i[show create], controller: :feedback

  resources :badges, only: :index do

    collection do
      get :own
    end
  end
  
  resources :tests, only: :index do
    
    member do
      post :start
    end
  end
  
  namespace :admin do
    resources :badges
    resources :rules
    root to: 'tests#index'
    get 'gists', to: "gists#index" 
    resources :tests do
      patch 'update_inline', to: "tests#update_inline", on: :member
      resources :questions, except: [:index], shallow: true do
        resources :answers, except: [:index], shallow: true
      end
    end
  end
  
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post 'gists', to: "gists#create"
    end
  end
      
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  
  validates :body, presence: true
  validate :validate_answers_quantity, on: :create
  
  scope :correct, -> { where(correct: true) }
  
  private

  def validate_answers_quantity
    errors.add(:question, 'не может иметь больше 4 ответов') if question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController

  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[edit update destroy]

  def new
    @answer = @question.answers.build
  end

  def create
    @answer = @question.answers.build(answer_params)

    if @answer.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private
  
  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end
  
  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %>
  <%= button_to 'Редактировать', edit_admin_answer_path(answer), method: :get %>
  <%= button_to 'Удалить', admin_answer_path(answer), method: :delete %><br>
</li>

app/views/admin/answers/_form.html.erb
<%= render 'shared/errors', resource: @answer %>
<%= form_with model: [:admin, @question, @answer] do |form| %>
  <div class="form_field">
    <%= form.label :body %><br>
    <%= form.text_area :body, rows: 5 %><br>
  </div>

  <div class="form_field">
    <%= form.label :correct %>
    <%= form.check_box :correct %><br>
  </div>

  <%= form.submit %>
<% end %>

app/views/admin/answers/edit.html.erb
<h1> Редактировать вопрос </h1>
<h2><%= @answer.question.body %></h2>

<%= render 'form' %>

<%= link_to 'Back', admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1> Создание нового ответа </h1>
<h2><%= @question.body %></h2>

<%= render 'form' %>

<%= link_to 'Back', admin_question_path(@question) %>