config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'
  
  devise_for :users, controllers: { sessions: 'users/sessions' }, path_names: {sign_in: :login, sign_out: :logout, sign_up: :signup}

  resource :feedback, only: %i[show create], controller: :feedback

  resources :badges, only: :index do

    collection do
      get :own
    end
  end
  
  resources :tests, only: :index do
    
    member do
      post :start
    end
  end
  
  namespace :admin do
    resources :badges
    resources :rules
    root to: 'tests#index'
    get 'gists', to: "gists#index" 
    resources :tests do
      patch 'update_inline', to: "tests#update_inline", on: :member
      resources :questions, except: [:index], shallow: true do
        resources :answers, except: [:index], shallow: true
      end
    end
  end
  
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post 'gists', to: "gists#create"
    end
  end
      
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
  
  before_validation :before_validation_set_position, on: :create

  private

  def before_validation_set_position
    self.position = self.test.questions.count + 1
  end

end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_question, only: %i[show destroy edit update]
  before_action :find_test, only: %i[new create]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def new
    @question = @test.questions.build
  end

  def create
    @question = @test.questions.build(question_params)

    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  private

  def rescue_with_test_not_found
    render html: '<h1>Вопрос не найден</h1>'.html_safe
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header
    if @question.new_record?
      "Create New #{@test.title} Question"
    else
      "Edit #{@question.test.title} Question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<h1><%= question_header %></h1>
<div>
  <%= render 'shared/errors', resource: @question %>
</div>
<%= form_with model: [:admin, @test, @question] do |form| %>
  <div class="form_field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
    
  <%= form.submit %>
<% end %>

app/views/admin/questions/_question.html.erb
<li>
  <%= link_to question.body, admin_question_path(question) %><br>
  <%= button_to 'Редактировать', edit_admin_question_path(question), method: :get %>
  <%= button_to 'Удалить', admin_question_path(question), method: :delete %><br>
</li>

app/views/admin/questions/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@question.test) %>

app/views/admin/questions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@test) %>

app/views/admin/questions/show.html.erb
<h1><%= @question.test.title %></h1>

<h2><%= @question.body %></h2>

<%= link_to 'Добавить ответ', new_admin_question_answer_path(@question) %>

<ul>
  <%= render @question.answers %>
</ul>

<%= link_to 'Back', admin_test_path(@question.test) %>