config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'
  
  devise_for :users, controllers: { sessions: 'users/sessions' }, path_names: {sign_in: :login, sign_out: :logout, sign_up: :signup}

  resource :feedback, only: %i[show create], controller: :feedback

  resources :badges, only: :index do

    collection do
      get :own
    end
  end
  
  resources :tests, only: :index do
    
    member do
      post :start
    end
  end
  
  namespace :admin do
    resources :badges
    resources :rules
    root to: 'tests#index'
    get 'gists', to: "gists#index" 
    resources :tests do
      patch 'update_inline', to: "tests#update_inline", on: :member
      resources :questions, except: [:index], shallow: true do
        resources :answers, except: [:index], shallow: true
      end
    end
  end
  
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post 'gists', to: "gists#create"
    end
  end
      
end

app/models/admin.rb
class Admin < User
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  
  validates :body, presence: true
  validate :validate_answers_quantity, on: :create
  
  scope :correct, -> { where(correct: true) }
  
  private

  def validate_answers_quantity
    errors.add(:question, 'не может иметь больше 4 ответов') if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users

  enum rule: { all_of_category: 'All of category',
               all_of_level: 'All of level',
               on_first_try: 'On first try' }
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(:title) }
  
  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
  
  before_validation :before_validation_set_position, on: :create

  private

  def before_validation_set_position
    self.position = self.test.questions.count + 1
  end

end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :category
  
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages, dependent: :destroy
  
  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  
  scope :level, -> (level) { where(level: level) }
  scope :easy_levels, -> { level(0..1) }
  scope :middle_levels, -> { level(2..4) }
  scope :hard_levels, -> { level(5..Float::INFINITY) }
  scope :with_category, -> (category) { where(category_id: category) }
  
  def self.show_tests(category)
    Test.with_category(category).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATIO = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question
  before_validation :before_validation_set_time_left, unless: Proc.new { test.timer.nil? }

  def completed?
    current_question.nil? || timesUp?
  end

  def passed?
    result >= SUCCESS_RATIO
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end
  
  def calculate_result
    update_columns(result: correct_questions * 100.0 / test.questions.count)
    update_columns(passed: true) if result >= SUCCESS_RATIO
  end

  def progress
    if current_question
      ((test.questions.index(current_question).to_f) / test.questions.length * 100).round
    else
      100
    end
  end

  private

  def before_validation_set_time_left
    if created_at
      self.time_left = (created_at + test.timer.seconds) - Time.current
    else
      self.time_left = test.timer
    end
  end
  
  def before_validation_set_current_question
    self.current_question = next_question
  end
  
  def next_question
    if current_question.present?
      test.questions.order(:position).where('position > ?', current_question.position).first
    else
      current_question = test.questions.find_by(position: 1)
    end
  end
  
  def correct_answer?(answer_ids)
    false
    
    correct_answer.ids.sort == answer_ids.map(&:to_i).sort if answer_ids
  end
  
  def correct_answer
    current_question.answers.correct
  end

  def timesUp?
    time_left <= 0 if test.timer
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable

  has_many :created_tests, class_name: 'Test', foreign_key: "author_id", dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages, dependent: :destroy
  has_many :gists, dependent: :destroy

  has_and_belongs_to_many :badges

  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP, 
                                                message: 'Введите корректный email'}

  def show_test_passage(level = 0..10)
    tests.level(level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController

  def create
    @question = TestPassage.find(params[:id]).current_question
    
    result = GistQuestionService.new(@question).call

    if result.success?
      flash_options = { success: t('.success_html', gist_url: result.gist_url) }
      current_user.gists.create!(question: @question, url: result.gist_url)
    else
      flash_options = { danger: result.error_message }
    end

    redirect_to test_passage_path(params[:id]), flash_options
  end
  
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  def index
    @tests = Test.all
  end

  def start
    @test = Test.find(params[:id])

    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo = nil)
    if repo
      link_to repo, "https://github.com/#{author.delete(' ')}/#{repo}", target: "_blank"
    else
      link_to author, "https://github.com/#{author.delete(' ')}", target: "_blank"
    end
  end
  
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header
    if @question.new_record?
      "Create New #{@test.title} Question"
    else
      "Edit #{@question.test.title} Question"
    end
  end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/_admin_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-end">
  <div class="container-fluid">
    <%= link_to 'Test-app', root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Gists', admin_gists_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Badges', admin_badges_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= content_tag :p, 'Admin', class: 'navbar-brand my-0' %>
      </li>
      <li class="nav-item">
        <%= content_tag :p, t('greetings', user: current_user.name), class: 'navbar-text m-0' %>
      </li>
      <li class="nav-item">
        <%= button_to t('logout'), destroy_user_session_path, method: :delete, class: 'btn btn-outline-light mx-2' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_footer.en.html.erb
<% author = 'Ilya Palaguto' %>
<% repo = 'Test-app' %>
<div class="footer">
  <small>
    <p>
      Devoloped by <%= github_url(author) %> 
    </p>
    <p><%= current_year %></p>
    <p><%= github_url(author, repo) %></p>
    <p>
      Education project in <%= link_to 'Thinknetica', 'https://thinknetica.com/', target: '_blank'%>
    </p>
  </small>
</div>

app/views/layouts/_footer.html.erb
<% author = 'Ilya Palaguto' %>
<% repo = 'Test-app' %>
<div class="footer">
  <small>
    <p>
      Devoloped by <%= github_url(author) %> 
    </p>
    <p><%= current_year %></p>
    <p><%= github_url(author, repo) %></p>
    <p>
      Учебный проект в онлайн-школе <%= link_to 'Thinknetica', 'https://thinknetica.com/', target: '_blank'%>
    </p>
  </small>
</div>

app/views/layouts/_footer.ru.html.erb
<% author = 'Ilya Palaguto' %>
<% repo = 'Test-app' %>
<div class="footer">
  <small>
    <p>
      Разработан <%= github_url(author) %> 
    </p>
    <p><%= current_year %></p>
    <p><%= github_url(author, repo) %></p>
    <p>
      Учебный проект в онлайн-школе <%= link_to 'Thinknetica', 'https://thinknetica.com/', target: '_blank'%>
    </p>
  </small>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light justify-content-end">
  <div class="container-fluid">
    <%= link_to 'Test-app', root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to t('admin_panel'), admin_root_path, class: 'nav-link' if current_user.is_a?(Admin) %>
        </li>
        <li class="nav-item">
          <%= link_to t('feed_back'), feedback_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Значки", own_badges_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
    <ul class="nav justify-content-end">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= content_tag :p, t("greetings", user: current_user.name), class: 'navbar-text m-0' %>
        </li>
        <li class="nav-item">
          <%= button_to t('logout'), destroy_user_session_path, method: :delete, class: 'btn btn-outline-dark mx-2' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to t('signup'), new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('login'), new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/admin_navigation" %>

    <div class='container'>
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAwesomeApp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>

    <div class='container'>
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <ul>
      <% resource.errors.full_messages.each {|error| %>
        <li><%= error %></li>
      <% } %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag :p, message.html_safe, class: "alert alert-#{type} mt-3" %>
<% end %>